from datetime import datetime
from app.extensions import db


class SalesStockCompositionAnalysisSnapshot(db.Model):
    __tablename__ = 'sales_stock_composition_analysis_snapshots'

    id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    source_id = db.Column(db.Integer, index=True)
    date = db.Column(db.Date, index=True)
    branch_id = db.Column(db.Integer, index=True)
    location_name = db.Column(db.String(150), index=True)
    state_name = db.Column(db.String(100))
    item_definition_id = db.Column(db.Integer, index=True)
    make = db.Column(db.String(100), index=True)
    make_id = db.Column(db.Integer)
    master_collection = db.Column(db.String(100), index=True)
    master_collection_id = db.Column(db.Integer)
    collection = db.Column(db.String(150), index=True)
    collection_id = db.Column(db.Integer)
    sub_section = db.Column(db.String(100))
    sub_section_id = db.Column(db.Integer)
    classification = db.Column(db.String(100), index=True)
    classification_id = db.Column(db.Integer)
    section = db.Column(db.String(100), index=True)
    section_id = db.Column(db.Integer)
    type = db.Column(db.String(100))
    type_id = db.Column(db.Integer)
    group = db.Column(db.String(100))
    group_id = db.Column(db.Integer)
    group_category = db.Column(db.String(100))
    group_category_id = db.Column(db.Integer)
    sub_classification = db.Column(db.String(100))
    sub_classification_id = db.Column(db.Integer)
    division = db.Column(db.String(100))
    division_id = db.Column(db.Integer)
    purity = db.Column(db.Numeric(10, 4), index=True)
    purity_id = db.Column(db.Integer)
    gender = db.Column(db.String(50))
    gender_id = db.Column(db.Integer)
    screw_type = db.Column(db.String(50))
    screw_type_id = db.Column(db.Integer)
    wide_range = db.Column(db.String(100), index=True)
    wide_range_id = db.Column(db.Integer)
    size_label = db.Column(db.String(100))
    size_unit = db.Column(db.Text)
    size_id = db.Column(db.Integer)
    barcode = db.Column(db.String(100), index=True)
    gross_weight = db.Column(db.Numeric(15, 4), default=0)
    net_weight = db.Column(db.Numeric(15, 4), default=0)
    barcode_total_cost = db.Column(db.Numeric(18, 4), default=0)
    purchase_cost = db.Column(db.Numeric(18, 4), default=0)
    purchase_board_rate = db.Column(db.Numeric(15, 4), default=0)
    provision_qty = db.Column(db.Integer, default=0)
    weight = db.Column(db.Numeric(15, 4), default=0)
    provision_weight = db.Column(db.Numeric(15, 4), default=0)
    report_group = db.Column(db.String(100))
    invoice_type = db.Column(db.String(100))
    trans_type = db.Column(db.String(50), index=True)
    l1_category = db.Column(db.String(100))
    l2_category_type = db.Column(db.String(100))
    l3_category_code = db.Column(db.String(100))
    purchase_metal_value = db.Column(db.Numeric(18, 4), default=0)
    purchase_mc_value = db.Column(db.Numeric(18, 4), default=0)
    sale_mc_value = db.Column(db.Numeric(18, 4), default=0)
    gross_mc_value = db.Column(db.Numeric(18, 4), default=0)
    rate_tsk = db.Column(db.Numeric(15, 4), default=0)
    turn_over = db.Column(db.Numeric(18, 4), default=0)
    tsk = db.Column(db.Numeric(18, 4), default=0)
    total_tsk = db.Column(db.Numeric(18, 4), default=0)
    tax_app_trans_amount = db.Column(db.Numeric(18, 4), default=0)
    total_tsk_plusit_charge = db.Column(db.Numeric(18, 4), default=0)
    dhanteras_advance_yn = db.Column(db.String(10))
    dhanteras_red_benefit_yn = db.Column(db.String(10))
    anbaana_advance_yn = db.Column(db.String(10))
    anbaana_red_benefit_yn = db.Column(db.String(10))
    myk_sourced_yn = db.Column(db.String(10))
    ornament_category = db.Column(db.String(100))
    last_updated_at = db.Column(db.DateTime)
    uid = db.Column(db.String(64))
    synced_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)
